-- GENERATED by tools/gen_zharr_exchange.py - do not edit by hand.
--
-- MCT registration for the Zharr Exchange. MCT loads every .lua under
-- script/mct/settings/, so this file only ever runs when MCT is installed.

local mct = get_mct and get_mct()
if not mct then return end

local m = mct:register_mod("derpy_chd_zharr_exchange")
m:set_title("Zharr Exchange")
m:set_author("derpy")
m:set_description("Pick a difficulty, or Custom to set every value yourself. The Zharr Exchange's difficulty is fixed for the life of a campaign. Change it from the main menu before starting a new one. Note that the preset now owns the seven system switches as well as the numbers - if you had one of them turned off, it lives under Custom. In a multiplayer campaign these settings are ignored and every value is the shipped default on every machine - two players cannot be given different economies. The log options below still work.")

-- MCT HAS NO CAMPAIGN GATING OF ITS OWN. mct_option:set_context_specific is an
-- EMPTY function body and set_local_only is commented out end to end, so both read
-- as gating and gate nothing. This is the working route, and it is only the
-- WARNING: the campaign's real defence is the snapshot the script writes into the
-- save at the first FactionTurnStart, which outranks anything set here.
local IN_CAMPAIGN = __game_mode == __lib_type_campaign
local LOCK_REASON = "The Zharr Exchange's difficulty is fixed for the life of a campaign. Change it from the main menu before starting a new one."
local CUSTOM_ONLY = "Pick the Custom difficulty to set this yourself."

m:add_new_section("preset", "Difficulty")
m:add_new_section("systems", "Systems")
m:add_new_section("market", "Market")
m:add_new_section("houses", "Rival houses")
m:add_new_section("shares", "Shares")
m:add_new_section("hashut", "Tithes")
m:add_new_section("shocks", "War shocks")
m:add_new_section("race", "Race profile")
m:add_new_section("world", "The world")
m:add_new_section("features", "Features")
m:add_new_section("debug", "Debug")

local o_preset = m:add_new_option("preset", "dropdown")
o_preset:set_text("Difficulty")
o_preset:set_tooltip_text("The Zharr Exchange's difficulty is fixed for the life of a campaign. Change it from the main menu before starting a new one.")
o_preset:set_assigned_section("preset")
o_preset:add_dropdown_value("easy", "Easy", "For a first campaign. A thin spread, most of a bad stake returned, cheap storage, a slow and forgiving guild - and shares still paying double. Rent and the patron's tithe are off.", false)
o_preset:add_dropdown_value("default", "Default", "The Exchange as designed and as every previous build played.", true)
o_preset:add_dropdown_value("hard", "Hard", "High risk, high reward. Every edge that costs you widens, the guild moves three steps a turn, war closes the market sooner - and dividends and buyouts rise with it.", false)
o_preset:add_dropdown_value("ultra", "Ultra Capitalism", "The extreme. A quarter spread against a tenth floor, the guild moving five steps a turn on holdings that shift twice as hard, hostility to +60%, the market shutting when under a third of the guild is at war, the altar demanding from turn 5, and shocks reaching twelve steps and lingering. Shares pay 5% and a buyout pays double.", false)
o_preset:add_dropdown_value("custom", "Custom", "Every value below becomes live. Set them before you start a campaign; they are fixed once one is running.", false)
o_preset:set_default_value("default")

local o_ai_traders = m:add_new_option("ai_traders", "checkbox")
o_ai_traders:set_text("Rival houses trade")
o_ai_traders:set_tooltip_text("The other houses of your people buy and sell here too. They move prices and take the other side of your trades. Off: only you trade.")
o_ai_traders:set_default_value(true)
o_ai_traders:set_assigned_section("systems")

local o_ai_gold = m:add_new_option("ai_gold", "checkbox")
o_ai_gold:set_text("Rival houses use real gold")
o_ai_gold:set_tooltip_text("Houses fund trades from their own treasuries and receive yours, which helps or hurts their armies. Off, no gold moves to or from a house - their trading still moves prices, so the market still prices them, but neither side spends or gains treasury gold.")
o_ai_gold:set_default_value(true)
o_ai_gold:set_assigned_section("systems")

local o_refusal = m:add_new_option("refusal", "checkbox")
o_refusal:set_text("Houses can refuse to sell")
o_refusal:set_tooltip_text("A house that despises you and holds most of a good will not sell it. Selling is always open either way. Off, hostility is a markup only.")
o_refusal:set_default_value(true)
o_refusal:set_assigned_section("systems")

local o_war_lock = m:add_new_option("war_lock", "checkbox")
o_war_lock:set_text("War closes the Exchange")
o_war_lock:set_tooltip_text("Enough of the guild at war with you and the market shuts until you make peace.")
o_war_lock:set_default_value(true)
o_war_lock:set_assigned_section("systems")

local o_warehouse_rent = m:add_new_option("warehouse_rent", "checkbox")
o_warehouse_rent:set_text("Warehouse rent")
o_warehouse_rent:set_tooltip_text("0.5 gold per unit held per turn.")
o_warehouse_rent:set_default_value(true)
o_warehouse_rent:set_assigned_section("systems")

local o_hashut_demands = m:add_new_option("hashut_demands", "checkbox")
o_hashut_demands:set_text("The patron's demands")
o_hashut_demands:set_tooltip_text("The altar periodically demands a commodity tithe.")
o_hashut_demands:set_default_value(true)
o_hashut_demands:set_assigned_section("systems")

local o_trade_income = m:add_new_option("trade_income", "checkbox")
o_trade_income:set_text("Exchange prices drive trade income")
o_trade_income:set_tooltip_text("A commodity you produce trading high raises your trade income that turn.")
o_trade_income:set_default_value(true)
o_trade_income:set_assigned_section("systems")

local o_cross_bloc = m:add_new_option("cross_bloc", "checkbox")
o_cross_bloc:set_text("Trade shares across trading partners")
o_cross_bloc:set_tooltip_text("Houses of the cultures your people deal with are listed beside your own. Off, the board lists your own people only.")
o_cross_bloc:set_default_value(true)
o_cross_bloc:set_assigned_section("systems")

local o_ai_stance = m:add_new_option("ai_stance", "checkbox")
o_ai_stance:set_text("Houses react to your holdings")
o_ai_stance:set_tooltip_text("A large stake in a house warms it toward you; hoarding the goods it sells cools it. This sets a real strategic stance, reaching war targeting and deals, and replaces other scripted stances between you every turn. Off, your market position stays inside the Exchange.")
o_ai_stance:set_default_value(true)
o_ai_stance:set_assigned_section("systems")

local o_ai_world = m:add_new_option("ai_world", "checkbox")
o_ai_world:set_text("The world trades")
o_ai_world:set_tooltip_text("Every landholding faction holds commodities, and buys and sells them each turn. Off: only the fourteen houses trade.")
o_ai_world:set_default_value(true)
o_ai_world:set_assigned_section("systems")

local o_world_scarcity = m:add_new_option("world_scarcity", "checkbox")
o_world_scarcity:set_text("Supply can run out")
o_world_scarcity:set_tooltip_text("A purchase fails when no faction anywhere is holding that good. Off: you can always buy.")
o_world_scarcity:set_default_value(true)
o_world_scarcity:set_assigned_section("systems")

local o_ai_deals = m:add_new_option("ai_deals", "checkbox")
o_ai_deals:set_text("Factions offer you deals")
o_ai_deals:set_tooltip_text("Factions with something to buy or sell put a one-turn offer to you each turn, priced off market in your favour. Off: no offers are posted and the Deals page says so.")
o_ai_deals:set_default_value(true)
o_ai_deals:set_assigned_section("systems")

local o_world_bundles = m:add_new_option("world_bundles", "checkbox")
o_world_bundles:set_text("Positions supply armies")
o_world_bundles:set_tooltip_text("A faction holding iron, timber and obsidian replenishes its armies faster; one that has sold them short replenishes slower, and being at war doubles it either way. Applies to you and other factions alike. Off: no supply effect is applied to anyone, and any left over from a previous save is removed.")
o_world_bundles:set_default_value(true)
o_world_bundles:set_assigned_section("systems")

local o_ladder_step = m:add_new_option("ladder_step", "slider")
o_ladder_step:set_text("Price move per step")
o_ladder_step:set_tooltip_text("How far one step moves the price. 1.10 is a 10% move; higher means sharper swings both ways.")
o_ladder_step:slider_set_precision(2)
o_ladder_step:slider_set_min_max(1.02, 1.30)
o_ladder_step:slider_set_step_size(0.01, 2)
o_ladder_step:set_default_value(1.10)
o_ladder_step:set_assigned_section("market")

local o_spread = m:add_new_option("spread", "slider")
o_spread:set_text("Buy/sell spread")
o_spread:set_tooltip_text("The gap between what you pay and what you are paid. 0.10 means a lot sells back for 10% less than it cost at the same price.")
o_spread:slider_set_precision(2)
o_spread:slider_set_min_max(0.00, 0.40)
o_spread:slider_set_step_size(0.01, 2)
o_spread:set_default_value(0.10)
o_spread:set_assigned_section("market")

local o_l2_sell = m:add_new_option("l2_sell", "slider")
o_l2_sell:set_text("Forge goods sell back at")
o_l2_sell:set_tooltip_text("What Armaments and Raw Materials pay when sold, as a fraction of what a lot costs. 0.5 means 500 back on a 1000 lot. Limited in play to 1 / the price step above, so a round trip can never turn a profit.")
o_l2_sell:slider_set_precision(2)
o_l2_sell:slider_set_min_max(0.05, 0.95)
o_l2_sell:slider_set_step_size(0.05, 2)
o_l2_sell:set_default_value(0.50)
o_l2_sell:set_assigned_section("market")

local o_sell_floor = m:add_new_option("sell_floor", "slider")
o_sell_floor:set_text("Sell floor")
o_sell_floor:set_tooltip_text("However hostile the guild is, a sale never pays less than this fraction of the world price.")
o_sell_floor:slider_set_precision(2)
o_sell_floor:slider_set_min_max(0.05, 1.00)
o_sell_floor:slider_set_step_size(0.05, 2)
o_sell_floor:set_default_value(0.25)
o_sell_floor:set_assigned_section("market")

local o_pressure_per_rung = m:add_new_option("pressure_per_rung", "slider")
o_pressure_per_rung:set_text("Lots to move one step")
o_pressure_per_rung:set_tooltip_text("Net lots you must buy before your own trading pushes the price up one step. Lower means cornering a good is easier.")
o_pressure_per_rung:slider_set_precision(0)
o_pressure_per_rung:slider_set_min_max(1, 20)
o_pressure_per_rung:slider_set_step_size(1, 0)
o_pressure_per_rung:set_default_value(4)
o_pressure_per_rung:set_assigned_section("market")

local o_carry_per_unit = m:add_new_option("carry_per_unit", "slider")
o_carry_per_unit:set_text("Warehouse rent per unit")
o_carry_per_unit:set_tooltip_text("Gold charged each turn for every unit you hold. Needs Warehouse rent switched on.")
o_carry_per_unit:slider_set_precision(1)
o_carry_per_unit:slider_set_min_max(0.0, 3.0)
o_carry_per_unit:slider_set_step_size(0.1, 1)
o_carry_per_unit:set_default_value(0.5)
o_carry_per_unit:set_assigned_section("market")

local o_ai_gain = m:add_new_option("ai_gain", "slider")
o_ai_gain:set_text("Rival price appetite")
o_ai_gain:set_tooltip_text("Price steps per unit of world appetite, before the limit. Higher means the guild moves prices harder on war and culture.")
o_ai_gain:slider_set_precision(1)
o_ai_gain:slider_set_min_max(0.0, 20.0)
o_ai_gain:slider_set_step_size(0.5, 1)
o_ai_gain:set_default_value(6.0)
o_ai_gain:set_assigned_section("houses")

local o_ai_max_rungs = m:add_new_option("ai_max_rungs", "slider")
o_ai_max_rungs:set_text("Rival steps per turn")
o_ai_max_rungs:set_tooltip_text("The most the guild can move one price in a single turn.")
o_ai_max_rungs:slider_set_precision(0)
o_ai_max_rungs:slider_set_min_max(0, 8)
o_ai_max_rungs:slider_set_step_size(1, 0)
o_ai_max_rungs:set_default_value(2)
o_ai_max_rungs:set_assigned_section("houses")

local o_book_per_rung = m:add_new_option("book_per_rung", "slider")
o_book_per_rung:set_text("Holdings per price step")
o_book_per_rung:set_tooltip_text("Units a house must hold to shift a price one step. Lower means the guild's positions move the market more.")
o_book_per_rung:slider_set_precision(0)
o_book_per_rung:slider_set_min_max(5, 100)
o_book_per_rung:slider_set_step_size(1, 0)
o_book_per_rung:set_default_value(30)
o_book_per_rung:set_assigned_section("houses")

local o_book_max = m:add_new_option("book_max", "slider")
o_book_max:set_text("Holdings step limit")
o_book_max:set_tooltip_text("The most steps the guild's holdings can shift a price, either way.")
o_book_max:slider_set_precision(0)
o_book_max:slider_set_min_max(0, 8)
o_book_max:slider_set_step_size(1, 0)
o_book_max:set_default_value(2)
o_book_max:set_assigned_section("houses")

local o_hostile_max = m:add_new_option("hostile_max", "slider")
o_hostile_max:set_text("Hostility markup limit")
o_hostile_max:set_tooltip_text("The most a house that despises you can add to a price. 0.25 is +25%.")
o_hostile_max:slider_set_precision(2)
o_hostile_max:slider_set_min_max(0.00, 1.00)
o_hostile_max:slider_set_step_size(0.05, 2)
o_hostile_max:set_default_value(0.25)
o_hostile_max:set_assigned_section("houses")

local o_friendly_max = m:add_new_option("friendly_max", "slider")
o_friendly_max:set_text("Friendly discount limit")
o_friendly_max:set_tooltip_text("The most a house that likes you can take off a price - it buys cheaper AND sells higher. Bounded by the buy/sell spread: at the default spread only about 1% gets through, and raising the spread raises this with it.")
o_friendly_max:slider_set_precision(2)
o_friendly_max:slider_set_min_max(0.00, 1.00)
o_friendly_max:slider_set_step_size(0.05, 2)
o_friendly_max:set_default_value(0.25)
o_friendly_max:set_assigned_section("houses")

local o_guild_close = m:add_new_option("guild_close", "slider")
o_guild_close:set_text("War closes the Exchange at")
o_guild_close:set_tooltip_text("Share of the guild's trade at war with you before the market shuts. Lower closes it more readily.")
o_guild_close:slider_set_precision(2)
o_guild_close:slider_set_min_max(0.10, 1.00)
o_guild_close:slider_set_step_size(0.05, 2)
o_guild_close:set_default_value(0.60)
o_guild_close:set_assigned_section("houses")

local o_refuse_share = m:add_new_option("refuse_share", "slider")
o_refuse_share:set_text("Refusal needs this supply share")
o_refuse_share:set_tooltip_text("A house must hold this much of a good, and despise you, before it will not sell it.")
o_refuse_share:slider_set_precision(2)
o_refuse_share:slider_set_min_max(0.10, 1.00)
o_refuse_share:slider_set_step_size(0.05, 2)
o_refuse_share:set_default_value(0.50)
o_refuse_share:set_assigned_section("houses")

local o_house_cash_max = m:add_new_option("house_cash_max", "slider")
o_house_cash_max:set_text("House gold limit per turn")
o_house_cash_max:set_tooltip_text("The most gold that can move to or from one house in a turn. House treasuries support their armies, so this limit stops a trading spree draining a house into poverty or making it rich overnight.")
o_house_cash_max:slider_set_precision(0)
o_house_cash_max:slider_set_min_max(0, 100000)
o_house_cash_max:slider_set_step_size(5000, 0)
o_house_cash_max:set_default_value(20000)
o_house_cash_max:set_assigned_section("houses")

local o_div_yield = m:add_new_option("div_yield", "slider")
o_div_yield:set_text("Dividend per share")
o_div_yield:set_tooltip_text("Paid every turn as a fraction of the live share price. 0.02 is 2%.")
o_div_yield:slider_set_precision(2)
o_div_yield:slider_set_min_max(0.00, 0.15)
o_div_yield:slider_set_step_size(0.01, 2)
o_div_yield:set_default_value(0.02)
o_div_yield:set_assigned_section("shares")

local o_buyout_premium = m:add_new_option("buyout_premium", "slider")
o_buyout_premium:set_text("Buyout payout")
o_buyout_premium:set_tooltip_text("What a share settles at when you absorb the house yourself. 1.25 pays 125% of its price.")
o_buyout_premium:slider_set_precision(2)
o_buyout_premium:slider_set_min_max(1.00, 3.00)
o_buyout_premium:slider_set_step_size(0.05, 2)
o_buyout_premium:set_default_value(1.25)
o_buyout_premium:set_assigned_section("shares")

local o_windup = m:add_new_option("windup", "slider")
o_windup:set_text("Wind-up payout")
o_windup:set_tooltip_text("What a share settles at when somebody else destroys the house. You backed a loser.")
o_windup:slider_set_precision(2)
o_windup:slider_set_min_max(0.00, 1.00)
o_windup:slider_set_step_size(0.05, 2)
o_windup:set_default_value(0.50)
o_windup:set_assigned_section("shares")

local o_seat_lost = m:add_new_option("seat_lost", "slider")
o_seat_lost:set_text("Price on losing a capital")
o_seat_lost:set_tooltip_text("A house that no longer holds its home region is priced at this fraction of its power.")
o_seat_lost:slider_set_precision(2)
o_seat_lost:slider_set_min_max(0.10, 1.00)
o_seat_lost:slider_set_step_size(0.05, 2)
o_seat_lost:set_default_value(0.60)
o_seat_lost:set_assigned_section("shares")

local o_demand_first_turn = m:add_new_option("demand_first_turn", "slider")
o_demand_first_turn:set_text("First tithe on turn")
o_demand_first_turn:set_tooltip_text("Nothing is demanded before this turn. Needs the patron's demands switched on.")
o_demand_first_turn:slider_set_precision(0)
o_demand_first_turn:slider_set_min_max(1, 100)
o_demand_first_turn:slider_set_step_size(1, 0)
o_demand_first_turn:set_default_value(15)
o_demand_first_turn:set_assigned_section("hashut")

local o_demand_cooldown = m:add_new_option("demand_cooldown", "slider")
o_demand_cooldown:set_text("Turns between tithes")
o_demand_cooldown:set_tooltip_text("Whether you paid or refused.")
o_demand_cooldown:slider_set_precision(0)
o_demand_cooldown:slider_set_min_max(3, 60)
o_demand_cooldown:slider_set_step_size(1, 0)
o_demand_cooldown:set_default_value(15)
o_demand_cooldown:set_assigned_section("hashut")

local o_demand_chance = m:add_new_option("demand_chance", "slider")
o_demand_chance:set_text("Tithe chance per turn")
o_demand_chance:set_tooltip_text("Per cent chance each turn once off cooldown.")
o_demand_chance:slider_set_precision(0)
o_demand_chance:slider_set_min_max(0, 100)
o_demand_chance:slider_set_step_size(5, 0)
o_demand_chance:set_default_value(30)
o_demand_chance:set_assigned_section("hashut")

local o_shock_gain = m:add_new_option("shock_gain", "slider")
o_shock_gain:set_text("Shock strength")
o_shock_gain:set_tooltip_text("Price steps per unit of world supply disrupted by a sack, a raze or a siege.")
o_shock_gain:slider_set_precision(0)
o_shock_gain:slider_set_min_max(0, 40)
o_shock_gain:slider_set_step_size(1, 0)
o_shock_gain:set_default_value(10)
o_shock_gain:set_assigned_section("shocks")

local o_shock_max = m:add_new_option("shock_max", "slider")
o_shock_max:set_text("Shock step limit")
o_shock_max:set_tooltip_text("The most steps one shock can move a price, either way.")
o_shock_max:slider_set_precision(0)
o_shock_max:slider_set_min_max(0, 20)
o_shock_max:slider_set_step_size(1, 0)
o_shock_max:set_default_value(6)
o_shock_max:set_assigned_section("shocks")

local o_shock_decay = m:add_new_option("shock_decay", "slider")
o_shock_decay:set_text("Shock decay per turn")
o_shock_decay:set_tooltip_text("What survives into the next turn. 0.5 halves it; higher makes a spike linger.")
o_shock_decay:slider_set_precision(2)
o_shock_decay:slider_set_min_max(0.00, 0.95)
o_shock_decay:slider_set_step_size(0.05, 2)
o_shock_decay:set_default_value(0.50)
o_shock_decay:set_assigned_section("shocks")

local o_race_strength = m:add_new_option("race_strength", "slider")
o_race_strength:set_text("Race profile strength")
o_race_strength:set_tooltip_text("How strongly your race's own market character applies on top of everything above. 0 turns it off and every race trades on the same numbers; 1 is as designed; 2 doubles it. Skaven gouge, refuse and delist harshly; the Empire is slow, civil and pays the best dividend; Cathay is the calmest board and the most taxed. Chaos Dwarfs are the baseline and never change.")
o_race_strength:slider_set_precision(2)
o_race_strength:slider_set_min_max(0.00, 2.00)
o_race_strength:slider_set_step_size(0.05, 2)
o_race_strength:set_default_value(1.00)
o_race_strength:set_assigned_section("race")

local o_world_cash_max = m:add_new_option("world_cash_max", "slider")
o_world_cash_max:set_text("World trader purse")
o_world_cash_max:set_tooltip_text("The most gold one faction outside the guild will move in a single turn.")
o_world_cash_max:slider_set_precision(0)
o_world_cash_max:slider_set_min_max(0, 50000)
o_world_cash_max:slider_set_step_size(500, 0)
o_world_cash_max:set_default_value(3000)
o_world_cash_max:set_assigned_section("world")

local o_world_trade_max = m:add_new_option("world_trade_max", "slider")
o_world_trade_max:set_text("World trade size")
o_world_trade_max:set_tooltip_text("The most lots one faction outside the guild will buy or sell in a single turn.")
o_world_trade_max:slider_set_precision(0)
o_world_trade_max:slider_set_min_max(1, 10)
o_world_trade_max:slider_set_step_size(1, 0)
o_world_trade_max:set_default_value(3)
o_world_trade_max:set_assigned_section("world")

local o_world_gain = m:add_new_option("world_gain", "slider")
o_world_gain:set_text("World trading weight")
o_world_gain:set_tooltip_text("How hard the wider world's holdings push a price. 0 means the world trades but its positions never move the board.")
o_world_gain:slider_set_precision(1)
o_world_gain:slider_set_min_max(0.0, 20.0)
o_world_gain:slider_set_step_size(0.5, 1)
o_world_gain:set_default_value(4.0)
o_world_gain:set_assigned_section("world")

local o_deal_max = m:add_new_option("deal_max", "slider")
o_deal_max:set_text("Deals offered per turn")
o_deal_max:set_tooltip_text("How many one-turn offers the world puts to you each turn. Every one is a decision to read, so this is small on purpose. Needs the offers switch on.")
o_deal_max:slider_set_precision(0)
o_deal_max:slider_set_min_max(1, 6)
o_deal_max:slider_set_step_size(1, 0)
o_deal_max:set_default_value(3)
o_deal_max:set_assigned_section("world")

local o_deal_edge = m:add_new_option("deal_edge", "slider")
o_deal_edge:set_text("Deal edge, per cent")
o_deal_edge:set_tooltip_text("How far off market an offer is priced, always in your favour: a buyer pays over, a seller takes under. Keep it under one price step or a deal becomes a free round trip against the market.")
o_deal_edge:slider_set_precision(0)
o_deal_edge:slider_set_min_max(1, 25)
o_deal_edge:slider_set_step_size(1, 0)
o_deal_edge:set_default_value(6)
o_deal_edge:set_assigned_section("world")

local o_pos_step = m:add_new_option("pos_step", "slider")
o_pos_step:set_text("War-goods position step")
o_pos_step:set_tooltip_text("How many lots of net iron, timber and obsidian one supply tier is worth. Lower means more factions carry a war-supply bonus or penalty; higher means only the biggest positions register.")
o_pos_step:slider_set_precision(0)
o_pos_step:slider_set_min_max(1, 12)
o_pos_step:slider_set_step_size(1, 0)
o_pos_step:set_default_value(4)
o_pos_step:set_assigned_section("world")

local ECONOMIC = {
    "ai_traders", "ai_gold", "refusal", "war_lock",
    "warehouse_rent", "hashut_demands", "trade_income", "cross_bloc",
    "ai_stance", "ai_world", "world_scarcity", "ai_deals",
    "world_bundles", "ladder_step", "spread", "l2_sell",
    "sell_floor", "pressure_per_rung", "carry_per_unit", "ai_gain",
    "ai_max_rungs", "book_per_rung", "book_max", "hostile_max",
    "friendly_max", "guild_close", "refuse_share", "house_cash_max",
    "div_yield", "buyout_premium", "windup", "seat_lost",
    "demand_first_turn", "demand_cooldown", "demand_chance", "shock_gain",
    "shock_max", "shock_decay", "race_strength", "world_cash_max",
    "world_trade_max", "world_gain", "deal_max", "deal_edge",
    "pos_step",
}

local function relock()
    local custom = o_preset:get_finalized_setting() == "custom"
    for _, k in ipairs(ECONOMIC) do
        local o = m:get_option_by_key(k)
        if o then
            if IN_CAMPAIGN then
                o:set_locked(true, LOCK_REASON)
            elseif not custom then
                o:set_locked(true, CUSTOM_ONLY)
            else
                o:set_locked(false)
            end
        end
    end
    if IN_CAMPAIGN then o_preset:set_locked(true, LOCK_REASON) end
end

-- The callback fires on MctOptionSelectedSettingSet, BEFORE the value is
-- finalized, so it reads the selected setting rather than the finalized one.
o_preset:add_option_set_callback(function(opt)
    local custom = opt:get_selected_setting() == "custom"
    for _, k in ipairs(ECONOMIC) do
        local o = m:get_option_by_key(k)
        if o and not IN_CAMPAIGN then
            if custom then o:set_locked(false)
            else o:set_locked(true, CUSTOM_ONLY) end
        end
    end
end)
core:add_listener("derpy_chd_ex_mct_ready", "MctFinalized", true,
    function() relock() end, false)
relock()

local o_feat_deep_history = m:add_new_option("feat_deep_history", "checkbox")
o_feat_deep_history:set_text("Price history chart")
o_feat_deep_history:set_tooltip_text("The forty-turn chart on the Trade view's second page. Off greys the page arrows and the panel stops drawing it - the history itself keeps being recorded, so turning this back on shows the turns you were away rather than a flat line.")
o_feat_deep_history:set_default_value(true)
o_feat_deep_history:set_assigned_section("features")

local o_feat_demand_shocks = m:add_new_option("feat_demand_shocks", "checkbox")
o_feat_demand_shocks:set_text("War demand shocks")
o_feat_demand_shocks:set_tooltip_text("A sacked or besieged settlement moving the price of what it made, and the Shaken line in the footer. Off and prices move only on supply, trade and the guild.")
o_feat_demand_shocks:set_default_value(true)
o_feat_demand_shocks:set_assigned_section("features")

local o_feat_appetite_drift = m:add_new_option("feat_appetite_drift", "checkbox")
o_feat_appetite_drift:set_text("World appetite")
o_feat_appetite_drift:set_tooltip_text("Cultures wanting more of some goods than they make, drifting over the campaign - the Wanted and Unwanted lines. Off and every good is priced on supply alone.")
o_feat_appetite_drift:set_default_value(true)
o_feat_appetite_drift:set_assigned_section("features")

local o_feat_orders = m:add_new_option("feat_orders", "checkbox")
o_feat_orders:set_text("Standing orders")
o_feat_orders:set_tooltip_text("Limit and stop orders on the Trade view's third page, filled at your turn start. Off and the page is gone and nothing fills - orders you have already placed are kept, not cancelled, and start filling again when you turn this back on.")
o_feat_orders:set_default_value(true)
o_feat_orders:set_assigned_section("features")

local o_allow_uncommercial = m:add_new_option("allow_uncommercial", "checkbox")
o_allow_uncommercial:set_text("Let cultures without markets trade")
o_allow_uncommercial:set_tooltip_text("Tomb Kings, both vampire cultures, Nagash's Undead Legions, the four Chaos gods, Daemons of Chaos, Beastmen and Lizardmen. They keep no markets in lore, so when off, they have no Exchange at all: no button, no panel, no prices. Others can still buy shares in them either way. Takes effect on a restart.")
o_allow_uncommercial:set_default_value(false)
o_allow_uncommercial:set_assigned_section("features")

local o_allow_raiders = m:add_new_option("allow_raiders", "checkbox")
o_allow_raiders:set_text("Let raider cultures trade")
o_allow_raiders:set_tooltip_text("Greenskins, Norsca and the Warriors of Chaos. They take rather than trade, so when off, they have no Exchange at all. This does NOT remove them as investments: other cultures can still buy shares in them. Takes effect on a restart.")
o_allow_raiders:set_default_value(false)
o_allow_raiders:set_assigned_section("features")

local o_log_level = m:add_new_option("log_level", "dropdown")
o_log_level:set_text("Log detail")
o_log_level:set_tooltip_text("How much the Exchange writes to script_log.txt. Changeable at any time, including mid-campaign - unlike everything above.")
o_log_level:set_assigned_section("debug")
o_log_level:add_dropdown_value("off", "Off", "Nothing at all, including failures. Not recommended.", false)
o_log_level:add_dropdown_value("errors", "Errors only", "Only the lines that report something going wrong.", false)
o_log_level:add_dropdown_value("normal", "Normal", "What the mod has always logged.", true)
o_log_level:add_dropdown_value("verbose", "Verbose", "Everything, including per-step detail.", false)
o_log_level:set_default_value("normal")

local o_log_turn = m:add_new_option("log_turn", "checkbox")
o_log_turn:set_text("Turn summaries")
o_log_turn:set_tooltip_text("Rent charged, dividends paid, settings locked.")
o_log_turn:set_default_value(true)
o_log_turn:set_assigned_section("debug")

local o_log_trade = m:add_new_option("log_trade", "checkbox")
o_log_trade:set_text("Your trades")
o_log_trade:set_tooltip_text("Buys, sells, offerings and why one was refused.")
o_log_trade:set_default_value(true)
o_log_trade:set_assigned_section("debug")

local o_log_price = m:add_new_option("log_price", "checkbox")
o_log_price:set_text("Prices")
o_log_price:set_tooltip_text("Repricing, supply and trade income.")
o_log_price:set_default_value(true)
o_log_price:set_assigned_section("debug")

local o_log_house = m:add_new_option("log_house", "checkbox")
o_log_house:set_text("Houses")
o_log_house:set_tooltip_text("Delistings, settlements and pruning.")
o_log_house:set_default_value(true)
o_log_house:set_assigned_section("debug")

local o_log_demand = m:add_new_option("log_demand", "checkbox")
o_log_demand:set_text("The tithe")
o_log_demand:set_tooltip_text("Demands, payments and wrath.")
o_log_demand:set_default_value(true)
o_log_demand:set_assigned_section("debug")

local o_log_shock = m:add_new_option("log_shock", "checkbox")
o_log_shock:set_text("War shocks")
o_log_shock:set_tooltip_text("Sacks, razes and sieges moving a price.")
o_log_shock:set_default_value(true)
o_log_shock:set_assigned_section("debug")

local o_log_ui = m:add_new_option("log_ui", "checkbox")
o_log_ui:set_text("Panel")
o_log_ui:set_tooltip_text("The panel, the opener button and the finance screen.")
o_log_ui:set_default_value(true)
o_log_ui:set_assigned_section("debug")

m:add_new_action("dump_state", "Dump state to log", function()
    core:trigger_custom_event("ZharrExchangeDumpState", {})
end):set_assigned_section("debug")

m:add_new_action("dump_supply", "Re-run supply scan", function()
    core:trigger_custom_event("ZharrExchangeDumpSupply", {})
end):set_assigned_section("debug")

